baseURL = 'https://zijieyanhw.github.io/MIGN/'
languageCode = 'zh-CN'
title = 'My New Hugo Site'
theme = 'reimu'

# 添加这些配置
canonifyURLs = true
relativeURLs = false

defaultContentLanguage = 'zh-CN'
[languages]
[languages.en]
languageName = 'English'
weight = 1
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true
[languages.zh-TW]
languageName = '繁體中文'
weight = 1
hasCJKLanguage = true
[languages.ja]
languageName = '日本語'
weight = 1
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true